services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: som-api
    environment:
      - "DatabaseSettings__ConnectionString=Server=som-db;Database=AACSB;\
        User=sa;Password=$uper$ecureP@$$w0rd;MultipleActiveResultSets=true"
      - "DatabaseSettings__DBProvider=mssql"
      - "HangfireSettings__Storage__ConnectionString=Server=som-db;Database=AACSB;\
        User=sa;Password=$uper$ecureP@$$w0rd;MultipleActiveResultSets=true"
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=aacsb2023"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aacsb.pfx"
      - "CorsSettings__Angular=https://aacsb-api.example.com"
    labels:
      # Watchtower
      com.centurylinklabs.watchtower.enable: "true"
      com.centurylinklabs.watchtower.local-image: "true"
    volumes:
      - ~/som-api/Logs:/app/Logs
      - ~/som-api/Files:/app/Files
    ports:
      - "5050:5050"
      - "5060:5060"
    depends_on:
      - db
    restart: on-failure
    networks:
      - som-network
  db:
    image: "mcr.microsoft.com/azure-sql-edge"
    container_name: som-db
    restart: always
    environment:
      MSSQL_SA_PASSWORD: "$uper$ecureP@$$w0rd"
      SA_PASSWORD: "$uper$ecureP@$$w0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - azure-sql-storage:/var/opt/mssql
    networks:
      - som-network

networks:
  som-network:
    external: true

volumes:
  azure-sql-storage:
    external: true